version: "3"
services:
  ms-db:
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ribeiro
  users:
    image: fabiopina151/registerwitheureka_users-ms:latest
    expose:
      - "5000"
    links:
      - ms-db
    environment:
      - DATABASEADDRESS=ms-db:3306
  songs:
    image: fabiopina151/registerwitheureka_songs-ms:latest
    expose:
      - "5001"
    links:
      - ms-db
    environment:
      - DATABASEADDRESS=ms-db:3306
  playlists:
    image: fabiopina151/registerwitheureka_playlists-ms:latest
    expose:
      - "5002"
    links:
      - ms-db
      - songs
    environment:
      - DATABASEADDRESS=ms-db:3306
      - SONGSADDRESS=songs:5001
  auth:
    image: fabiopina151/registerwitheureka_auth-ms:latest
    expose:
      - "5003"
    links:
      - users
    environment:
      - USERSADDRESS=users:5000
  aggr:
    image: fabiopina151/registerwitheureka_aggr-ms:latest
    expose:
      - "5004"
    links:
      - playlists
      - songs
    environment:
      - PLAYLISTSADDRESS=playlists:5002
      - SONGSADDRESS=songs:5001

